[project]
name = "tutor-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Vicente Marçal", email = "vicente.marcal@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
tutor-rag = "tutor_rag:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
